language: ruby

rvm:
  - 2.2.5

services:
  - mysql

before_install:
  - gem update --system
  - gem --version
  - gem install bundler
  - bundler --version

script:
  - travis_wait ./travis-build.rb
  - cd stash_engine && bundle install && bundle exec rake



